# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package manifests
COPY package.json package-lock.json ./

# Install dependencies (ignore scripts to skip postinstall if any)
RUN npm install --ignore-scripts

# Copy all sources
COPY . .

# Build the project
RUN npm run build

# Expose necessary port if needed (not required for stdio MCP)

# Start the MCP server
CMD [ "npm", "start" ]
